// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3dumVs-jsNA027_6QjsIRL_qnRxA5O0M',
    appId: '1:445448526310:web:ba52c950b035a670521e27',
    messagingSenderId: '445448526310',
    projectId: 'eazy-travel-56a29',
    authDomain: 'eazy-travel-56a29.firebaseapp.com',
    storageBucket: 'eazy-travel-56a29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Q9NxqkVDjYnhvwkfbZ9feIYNQehAT6Y',
    appId: '1:445448526310:android:d56625f07dd0e28b521e27',
    messagingSenderId: '445448526310',
    projectId: 'eazy-travel-56a29',
    storageBucket: 'eazy-travel-56a29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH6vEEmnfF5d1cqN1B-6tF-4u25oZrHSs',
    appId: '1:445448526310:ios:6ea7adf166dd6c0d521e27',
    messagingSenderId: '445448526310',
    projectId: 'eazy-travel-56a29',
    storageBucket: 'eazy-travel-56a29.appspot.com',
    iosBundleId: 'eazytravel.com.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH6vEEmnfF5d1cqN1B-6tF-4u25oZrHSs',
    appId: '1:445448526310:ios:c8035515a28c5cf5521e27',
    messagingSenderId: '445448526310',
    projectId: 'eazy-travel-56a29',
    storageBucket: 'eazy-travel-56a29.appspot.com',
    iosBundleId: 'eazytravel.com.project1.RunnerTests',
  );
}
